version: '3'
services:
    kerberosserver:
        container_name: kerberosserver
        build: 
            context: ./kerberosserver
            args:
                - REALM=${REALM}
                - PROXY=${PROXY}
        volumes:
             - ./kerberosserver/config/krb5.conf:/etc/krb5.conf
             - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: kerberosserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.4
        command: [bash,-c,"/etc/init.d/heimdal-kdc start && while true; do date; ping -c 4 kerberosclient; sleep 180; done"]
    kerberosclient:
        container_name: kerberosclient
        build: 
            context: ./kerberosclient
            args:
                - PROXY=${PROXY}
        volumes:
            - ./kerberosclient/config/krb5.conf:/etc/krb5.conf
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf 
        hostname: kerberosclient
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.8
        command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 180; done"]
    centosclient:
        container_name: centosclient 
        build:
            context: ./centosclient
            args:
                - PROXY=${PROXY}
        volumes:
            - ./mitserver/config/krb5.conf:/etc/krb5.conf
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: centosclient
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.6
        command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 180; done"]
    sshserver:
        container_name: sshserver
        build:
            context: ./sshserver
            args:
                - PROXY=${PROXY}
        volumes:
            - ./sshserver/config/sshd_config:/etc/ssh/sshd_config
            - ./mitserver/config/krb5.conf:/etc/krb5.conf
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: sshserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.5
        ports:
            - "2222:22"
        command: [/usr/sbin/sshd,-D]
        #command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 180; done"]
    mitserver:
        container_name: mitserver
        build:
            context: ./mitserver
            args:
                - PROXY=${PROXY}
        volumes:
             - ./mitserver/config/krb5.conf:/etc/krb5.conf
             - ./mitserver/config/kdc.conf:/var/kerberos/krb5kdc/kdc.conf
             - ./mitserver/config/kadm5.acl:/var/kerberos/krb5kdc/kadm5.acl
             - ./mitserver/logs/krb5libs.log:/var/log/krb5libs.log
             - ./mitserver/logs/krb5kdc.log:/var/log/krb5kdc.log
             - ./mitserver/logs/kadmind.log:/var/log/kadmind.log
             - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: mitserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.9        
        command: [bash,-c,"/usr/sbin/krb5kdc -P /var/run/krb5kdc.pid && /usr/sbin/_kadmind -P /var/run/kadmind.pid && while true; do date; ping -c 4 kerberosclient; sleep 180; done"]
    dnsserver:
        container_name: dnsserver
        build:
            context: ./dnsserver
            args:
                - PROXY=${PROXY}
        volumes:
            - ./dnsserver/config/named.conf:/etc/named.conf
            - ./dnsserver/config/named:/etc/named
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
            - ./dnsserver/scripts/moddns.sh:/scripts/moddns.sh
        hostname: dnsserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.7
        ports:
            - "53:53"
        command: [bash,-c,"/usr/sbin/named -u named -f -c /etc/named.conf"]

networks:
    skynet:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
