version: '3'
services:
    kerberosserver:
        build: 
            context: ./kerberosserver
            args:
                - REALM=${REALM}
                - PROXY=${PROXY}
        volumes:
             - ./kerberosserver/config/krb5.conf:/etc/krb5.conf
        hostname: kerberosserver
        domainname: mydomain.com
        command: [bash,-c,"/etc/init.d/heimdal-kdc start && while true; do date; ping -c 4 kerberosclient; sleep 30; done"]
    kerberosclient:
        build: 
            context: ./kerberosclient
            args:
                - PROXY=${PROXY}
        volumes:
            - ./kerberosclient/config/krb5.conf:/etc/krb5.conf
        hostname: kerberosclient
        domainname: mydomain.com
        command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 30; done"]
    centosclient:
        build:
            context: ./centosclient
            args:
                - PROXY=${PROXY}
        #volumes:
         #   - ./centosclient/config/krb5.conf:/etc/krb5.conf
        hostname: centosclient
        domainname: mydomain.com
        command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 30; done"]
