version: '3.3'
services:
    centosclient:
        container_name: centosclient 
        build:
            context: ./centosclient
            args:
                - PROXY=${PROXY}
        volumes:
            - ./kerberosserver/config/krb5.conf:/etc/krb5.conf
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: centosclient
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.6
        command: [bash,-c,"while true; do date; ping -c 4 kerberosserver; sleep 180; done"]
    sshserver:
        container_name: sshserver
        build:
            context: ./sshserver
            args:
                - PROXY=${PROXY}
        volumes:
            - ./kerberosserver/config/krb5.conf:/etc/krb5.conf
            - ./sshserver/config/sshd_config:/etc/ssh/sshd_config
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: sshserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.5
        depends_on:
            - kerberosserver
        command: >
            bash -c "
                 kadmin -w ${PW} \
                        -q \"addprinc -randkey host/sshserver.mydomain.com\"
                 if ! klist -k /etc/krb5.keytab | grep -q sshserver ; then
                     kadmin -w ${PW} \
                            -q \"ktadd -k /etc/krb5.keytab host/sshserver.mydomain.com\";
                 fi
                 /usr/sbin/sshd -D"
    kerberosserver:
        container_name: kerberosserver
        build:
            context: ./kerberosserver
            args:
                - PROXY=${PROXY}
        volumes:
             - ./kerberosserver/config/krb5.conf:/etc/krb5.conf
             - ./kerberosserver/config/kdc.conf:/var/kerberos/krb5kdc/kdc.conf
             - ./kerberosserver/config/kadm5.acl:/var/kerberos/krb5kdc/kadm5.acl
             - ./kerberosserver/logs/krb5libs.log:/var/log/krb5libs.log
             - ./kerberosserver/logs/krb5kdc.log:/var/log/krb5kdc.log
             - ./kerberosserver/logs/kadmind.log:/var/log/kadmind.log
             - ./dnsserver/config/resolv.conf:/etc/resolv.conf
        hostname: kerberosserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.9        
        command: >
            bash -c "
                if kadmin.local listprincs| grep -q testuser; then
                    kdb5_util create -s -P ${PW}
                    kadmin.local -q \"addprinc -pw ${PW} testuser\"
                    kadmin.local -q \"addprinc -pw ${PW} root/admin\"
                fi
                /usr/sbin/krb5kdc
                /usr/sbin/kadmind -nofork"
    dnsserver:
        container_name: dnsserver
        build:
            context: ./dnsserver
            args:
                - PROXY=${PROXY}
        volumes:
            - ./dnsserver/config/named.conf:/etc/named.conf
            - ./dnsserver/config/named:/etc/named
            - ./dnsserver/config/resolv.conf:/etc/resolv.conf
            - ./dnsserver/scripts/moddns.sh:/scripts/moddns.sh
        hostname: dnsserver
        domainname: mydomain.com
        networks:
            skynet:
                ipv4_address: 172.20.0.7
        command: [bash,-c,"/usr/sbin/named -u named -f -c /etc/named.conf"]

networks:
    skynet:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
